### ISSUE TITLE
Look for function as a method in the class

### ISSUE THREAD

**Issue by ctgraham** [marcbria/blockUsers#1]
I think you want this
https://github.com/marcbria/blockUsers/blob/ea7490cc16352627f549f299e2e8308063c0e859/BlockUsersPlugin.inc.php#L115

to be:
`if (method_exists($userDao, 'getByEmail')) {`

Otherwise it will look for 'getByEmail' within the current executing scope.

**Comment by marcbria** [comment]
Thanks Clinton.
